# Generated by Django 2.2.2 on 2019-06-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_page_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=125)),
                ('article_video', models.TextField()),
                ('article_tag', models.CharField(max_length=25)),
                ('article_funny', models.CharField(max_length=125)),
                ('article_comment', models.CharField(max_length=125)),
                ('article_author', models.CharField(max_length=125)),
                ('article_author_profile', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='new_page_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=75)),
                ('user_pic', models.CharField(max_length=125)),
                ('content', models.TextField()),
                ('funny', models.CharField(max_length=125)),
                ('comment_count', models.TextField()),
                ('comment_user', models.CharField(max_length=75)),
                ('comment_text', models.CharField(max_length=255)),
                ('comment_dianzhan', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='particulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_title', models.CharField(max_length=125)),
                ('details_date', models.CharField(max_length=55)),
                ('details_funny', models.CharField(max_length=50)),
                ('details_content', models.TextField()),
                ('details_Published_address', models.CharField(max_length=125)),
                ('details_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_page_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=75)),
                ('user_pic', models.CharField(max_length=125)),
                ('recommendations', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('liveness', models.CharField(max_length=255)),
                ('date_publish', models.CharField(max_length=125)),
                ('likesm', models.CharField(max_length=125)),
            ],
        ),
    ]
