# Generated by Django 2.2.2 on 2019-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbsk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qbsk2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_title', models.CharField(blank=True, max_length=255, null=True)),
                ('details_date', models.CharField(blank=True, max_length=255, null=True)),
                ('details_funny', models.CharField(blank=True, max_length=255, null=True)),
                ('details_content', models.TextField(blank=True, null=True)),
                ('details_published_address', models.CharField(blank=True, db_column='details_Published_address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'qbsk_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qbsk3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=125, null=True)),
                ('user_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('funny', models.CharField(blank=True, max_length=125, null=True)),
                ('comment_count', models.CharField(blank=True, max_length=125, null=True)),
                ('comment_user', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('comment_dianzhan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qbsk_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qbsk4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('liveness', models.CharField(blank=True, max_length=125, null=True)),
                ('date_publish', models.CharField(blank=True, max_length=255, null=True)),
                ('likesm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qbsk_4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qsbk1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=255, null=True)),
                ('article_video', models.CharField(blank=True, max_length=255, null=True)),
                ('article_tag', models.CharField(blank=True, max_length=20, null=True)),
                ('article_funny', models.CharField(blank=True, max_length=20, null=True)),
                ('article_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('article_author', models.CharField(blank=True, max_length=125, null=True)),
                ('article_author_profile', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'db_table': 'qsbk_1',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='home_page_data',
        ),
        migrations.DeleteModel(
            name='new_page_data',
        ),
        migrations.DeleteModel(
            name='particulars',
        ),
        migrations.DeleteModel(
            name='user_page_data',
        ),
    ]
